public with sharing class savebookingdetails {
    @AuraEnabled   
    public static void saverecords()
    {
    //     Truck_booking__c bookdetails=new Truck_booking__c();
    //     Id userId=UserInfo.getUserId();
    //     Account a=[select Id from Account where CreatedById=:userId];    
    //     bookdetails.Account__c=a;
    //     bookdetails.Truck__c='Ford Trucks 4142D';
    //   bookdetails.Pincode__c=36546;
    //   insert bookdetails;

     

    }
    public savebookingdetails() {

    }
}